name: Git Board - Commits

on:
  push:
    branches:
      - '**'

jobs:
  git-board-commits:
    name: Git Board - Commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Git Board - Commits
        uses: landamessenger/git-board@master
        with:
          action: commit
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-token-personal: ${{ secrets.REPO_PAT }}
          commit-prefix-builder: |
            branchName + "-world";


