name: Ensure Issue Id Title Format
on:
  issues:
    types: [opened, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-and-update-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check Issue Title Format
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.payload.issue.number;
            const issueTitle = context.payload.issue.title;

            const titlePattern = new RegExp(`^\\d+\\s*-\\s*`);
            if (!titlePattern.test(issueTitle)) {
              const formattedTitle = `${issueNumber} - ${issueTitle}`;
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                title: formattedTitle
              });
            }
