name: Ensure Issue Id Title Format
on:
  issues:
    types: [opened, edited]

jobs:
  check-and-update-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check Issue Title Format
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const issueTitle = context.payload.issue.title;
            const formattedTitle = `${issueNumber} - ${issueTitle.replace(/^\d+\s*-\s*/, '')}`;
            
            // Check if the current title matches the expected format
            if (issueTitle !== formattedTitle) {
              // Update the issue title to ensure it includes the issue number at the beginning
              await github.rest.issues.update({
                ...context.issue,
                title: formattedTitle
              });
            }
